### ISSUE TITLE
Volvo - Add Account Engagement Tracking Code to Volvo Website

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#535]
**Description**
The AE tracking code will enable us to be able to track the user engagement in the site and to be able to review these engagements in MCAE (Marketing Cloud Account Engagement).
The code will need to be provided from the MCAE team and the development team would need to place it before the body close tag on every page. If the tracking code can be embedded in the backend, then it would be dynamically added to all pages. 

**Use case:** User Engagement in Volvo Truck websites
As a marketer, I would like to see the user engagement for each page
Then I can review which pieces of content resonates and which ones don't
And then I can craft campaigns which pick up on user engagement patterns

**Acceptance Criteria**
- [x] Correct tracking code has been provided from the MCAE team
`<script type="text/javascript"> piAId = '1039333'; piCId = '25825'; piHostname = '[pi.pardot.com](https://pi.pardot.com/)'; (function() { function async_load(){ var s = document.createElement('script'); s.type = 'text/javascript'; s.src = ('https:' == document.location.protocol ? 'https://pi/' : 'http://cdn/') + '.[pardot.com/pd.js](https://pardot.com/pd.js)'; var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c); } if(window.attachEvent) { window.attachEvent('onload', async_load); } else { window.addEventListener('load', async_load, false); } })(); </script>`
- [x] Tracking code is embedded throughout the site before the body close tag on every page
- [x]  Check if the user has accepted targeting cookies to track him/her - OneTrust
- [ ] Testing to be done in analytics by the Volvo team

Add to Volvo

**Comment by ryanropero** [comment]
No they will each have their own.  Would you like me to add those ids here?

Ryan Ropero
Senior Business Analyst – Salesforce/Account Engagement
​
Volvo Group Digital & IT
Volvo Group Digitla & IT | Commercial Solutions NA​
T. 904 495 3717
7900 National Service Rd | Greensboro, NC, 27409 | USA
***@***.******@***.***>
***@***.***

**Comment by girishdigrajkar** [comment]
Validated on volvotrucks.us and no script displayed : 

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/ad584de6-cf79-40d5-bf06-3361d6b9e863)
