### ISSUE TITLE
Release: Sept 25

### ISSUE THREAD

**Issue by mollyaljenkins** [hlxsites/vg-volvotrucks-us#756]
### Volvo Trucks 

 Functional requirements
- [x] Social block changes https://github.com/hlxsites/vg-volvotrucks-us/issues/540 by @santi-homps in https://github.com/hlxsites/vg-volvotrucks-us/pull/743
Non-functional requirements
- [x] Fix newsfeed generator by @santi-homps in https://github.com/hlxsites/vg-volvotrucks-us/pull/753
- [x] Other changes
- [x] FR: [V2 Stories Carousel] Variant - Related Articles https://github.com/hlxsites/vg-volvotrucks-us/issues/541 by @cincplug in https://github.com/hlxsites/vg-volvotrucks-us/pull/736
- [ ] Multi language sites constants file location https://github.com/hlxsites/vg-volvotrucks-us/issues/733 by @santi-homps in https://github.com/hlxsites/vg-volvotrucks-us/pull/734
- [ ] Remove all caps from article cards block https://github.com/hlxsites/vg-volvotrucks-us/issues/702 by @santi-homps in https://github.com/hlxsites/vg-volvotrucks-us/pull/739
- [ ] Modify video helper to use videojs instead of iframe for AEM delivery videos by @yugandhar02 in https://github.com/hlxsites/vg-volvotrucks-us/pull/722
- [ ] NFR: Change Truck Configurator iFrame Integration to Enhanced Embed Solution https://github.com/hlxsites/vg-volvotrucks-us/issues/704 by @cincplug in https://github.com/hlxsites/vg-volvotrucks-us/pull/745
- [ ] 688 search using endpoint by @jonatan-lledo-netcentric in https://github.com/hlxsites/vg-volvotrucks-us/pull/732
- [ ] Fix v2 video block by @yugandhar02 in https://github.com/hlxsites/vg-volvotrucks-us/pull/751
- [ ] Fix embed block by @yugandhar02 in https://github.com/hlxsites/vg-volvotrucks-us/pull/750
- [ ] 704 discrepancy fixes by @cincplug in https://github.com/hlxsites/vg-volvotrucks-us/pull/752
- [ ] 704 input fixes by @cincplug in https://github.com/hlxsites/vg-volvotrucks-us/pull/754

### Mack Trucks

Functional requirements

- [ ] Multi language configuration https://github.com/hlxsites/vg-macktrucks-com/issues/862 by @santi-homps in https://github.com/hlxsites/vg-macktrucks-com/pull/866

Other changes

- [ ] V2 Pull Quote https://github.com/hlxsites/vg-macktrucks-com/issues/767 by @santi-homps in https://github.com/hlxsites/vg-macktrucks-com/pull/861

### Roadchoice

Functional requirements

- [ ] Hero Block https://github.com/aemsites/vg-roadchoice-com/issues/7 by @santi-homps in https://github.com/aemsites/vg-roadchoice-com/pull/8

Other changes

- [ ] Multi language sites configuration by @santi-homps in https://github.com/aemsites/vg-roadchoice-com/pull/5

- [ ] All development is available in the sidekick library
