### ISSUE TITLE
Release: Oct 9

### ISSUE THREAD

**Issue by mollyaljenkins** [hlxsites/vg-volvotrucks-us#772]
**Mack Trucks:** 
Functional requirements
- [ ] Delete spacing when one character is in italics https://github.com/hlxsites/vg-macktrucks-com/issues/773 by @santi-homps in https://github.com/hlxsites/vg-macktrucks-com/pull/881

Bugfixes
- [ ] Revert preload changes in release by @santi-homps in https://github.com/hlxsites/vg-macktrucks-com/pull/875

Other changes
- [ ] xss fixed & typo by @jonatan-lledo-netcentric in https://github.com/hlxsites/vg-macktrucks-com/pull/873

**Volvo Trucks**
Functional requirements
- [ ] Implement pagination module for v2-article-cards https://github.com/hlxsites/vg-volvotrucks-us/issues/602 by @amglebihan in https://github.com/hlxsites/vg-volvotrucks-us/pull/767

Non-functional requirements
- [ ] Adapt v2-video block for AEM videos by @yugandhar02 in https://github.com/hlxsites/vg-volvotrucks-us/pull/770

Bugfixes
- [ ] Hotfix magazine search by @jonatan-lledo-netcentric in https://github.com/hlxsites/vg-volvotrucks-us/pull/760
- [ ] Bugfix: Revert dynamic preloading constants file https://github.com/hlxsites/vg-volvotrucks-us/issues/762 by @santi-homps in https://github.com/hlxsites/vg-volvotrucks-us/pull/763
- [ ] Bugfix: Fix carousel arrows misalignment 761 by @cincplug in https://github.com/hlxsites/vg-volvotrucks-us/pull/764
- [ ] HotFix: image & author correctly checked by @jonatan-lledo-netcentric in https://github.com/hlxsites/vg-volvotrucks-us/pull/766

**RoadChoice**
Functional requirements

- [ ] Video implementation in hero https://github.com/aemsites/vg-roadchoice-com/issues/11 by @santi-homps in https://github.com/aemsites/vg-roadchoice-com/pull/12

Bugfixes

- [ ] Bugfix: Revert preload by @santi-homps in https://github.com/aemsites/vg-roadchoice-com/pull/16
